UKHomeOffice/vault-sidekick

main.go
vault_resources.go
vault_resources_test.go

- fixing the enviroment variable expansion to permit underscores

environment expansion fix

---

README.md
main.go
vault_resources.go
vault_resources_test.go

- switching to using the os.ExpandEnv methods rather than tokenizing the string
- updated the readme to reflect the changes

env expansion

---

README.md
auth_userpass.go

This change enables the use of environment variables for auth settings, i.e. for the userpass backend. The existing behavior is preserved where the authentication file is checked first, and only if the values are missing or empty will environment variables be checked. Variables are nested under `VAULT_SIDEKICK`, i.e. `VAULT_SIDEKICK_USERNAME`, `VAULT_SIDEKICK_PASSWORD`. 
This method of passing credentials should be much easier to integrate with kubernetes secrets.

enable env vars for auth settings

---

auth_approle.go
vault.go

This enables authenticating with the vault approle backend, using a `secret_id` and `role_id`. It uses the existing method of passing variables in the auth file, and in the spirit of #25 allows falling back to env vars.
Didn't combine this with the existing auth logic by path because the login paths used by userpass and app role are unique (userpass expects username in path) and accept different payloads.

enable authentication with approle backend

---

README.md
main.go
vault.go
vault_resource.go
vault_resources.go

This PR adds an optional 'retries' parameter to VaultResource. If it is not set, it should behave as now.
It behaves well with the recently added one-shot mode. The current 'modes' are:
* `retries` set and one-shot=true: will retry up to N times and then exit with a failure code if it's unsuccessful
* `retries` not set and one-shot=true: will retry indefinitely (as it does now)
* `retries` set and one-shot=false: will retry up to N times, and then stop attempting to process the event. If all items in the processing loop have reached maxRetries, vault-sidekick exits with code 1
* `retries` not set and one-shot=false: will retry indefinitely (as it does now) 
Closes #10

Add 'retries' parameter to resources to allow optional maxRetries

---

README.md
vault_resource.go
vault_resources.go
watched_resource.go

Currently there's no way (aside from randomising before calling vault-sidekick) to generate *slightly* random times to renew/update resources.
This PR adds a `jitter` field to CNs. If specified, a duration up to `jitter` will be subtracted from the renewal time for the resource. This is useful if you are running many replicas of the same application, with the same configuration, and do not want them reloading credentials/secrets simultaneously.
/cc @gambol99 
Closes #50

Add support for optional jitter parameter on CN

---

auth_aws_ec2.go
vault.go

Adds an `aws-ec2` auth backend, which uses the aws ec2 auth mechanism, getting the pkcs7 document from the metadata service - described here (https://www.vaultproject.io/api/auth/aws/index.html#login).
Includes an env var `VAULT_SIDEKICK_NONCE_FILE` to pull the client nonce from a file (https://www.vaultproject.io/docs/auth/aws.html#client-nonce).
I retained the copyright header from the rest of the files, not sure if you want to keep that, let me know.

auth: add aws-ec2 auth backend

---

config.go

Simply defaults to the value of env var `VAULT_AUTH_METHOD` instead of hard coding "token". Falls back to "token" if the env var is not set.

auth: allow setting auth method via env var

---

vault_resources.go

Allows overriding separator in the `-cn` flag.
Use case: I've got to request certs with `:` in the common name.

allow overriding separator string

---

utils.go

this allows more advanced usage without having to call a script
directly, e.g. `pkill {myapp}`. if there is only a single cmd
passed, then fallback to the existing behavior of passing the
filename as an argument.

utils: split exec args on space

---

auth_gcp_gce.go
vault.go

Adds an ```gcp-gce``` auth backend, which uses the gcp gce auth mechanism, getting the JWT token for the instance service account from the metadata service - described here (https://www.vaultproject.io/docs/auth/gcp.html#gce)

Add support for GCP/GCE authentication

---

README.md
auth_kubernetes.go
vault.go

This PR adds support for [Kubernetes auth](https://www.vaultproject.io/docs/auth/kubernetes.html). It accounts for auth backends that are enable at different paths with the `VAULT_K8S_LOGIN_PATH` environment variable, and non-default token mount locations with `VAULT_K8S_TOKEN_PATH`.
The only required environment variable is `VAULT_SIDEKICK_ROLE`, which specifies a role name against which to authenticate.
Closes #62.

Add Kubernetes auth backend

---

utils.go
utils_test.go

If the lease duration is one second `rand.Intn` will fail because it does not allow values which are <= 0

fix lease duration of one second

---

CHANGELOG.md
README.md
main.go
vault.go
vault_resource.go

The postgresql and mysql database backend are deprecated and the prefer way is to use the database backend.
All that is needed is to add the `database` key to the authorized resources to support it.

add support to the database backend

---

README.md
vault.go

The v2 kv secrets engine returns the secret data in a different format (https://www.vaultproject.io/api/secret/kv/kv-v2.html#sample-response-1) than v1, this means that vault-sidekick writes a string representation of a map with "data" and "metadata" keys to file, rather than the secret data.
This change introduces a check to identify if the secrets engine is a v1 or v2 response.

Support secrets from v2 kv store

---

formats.go

A first stab at fixing: - https://github.com/UKHomeOffice/vault-sidekick/issues/91
**Some questions about this solution**
* Should the ability to pull out the whole chain be optional?
* Should this be implemented as a new fmt or an additional flag or just done by default?
* Is it acceptable to write out the whole chain into a single file?
* What should the filename(s) be? currently I am appending .ca_chain.ca
**Other notes**
* I added a newline char between the certs when writing them to a single file. Should I use a localised/os specific carriage return?
* The code assumes that ca_cert is always an interface slice, the only other way I could think of was using reflection, but this is usually frowned upon. I looked at the vault code and it seems like this should always be a slice.

Create ca_chain file when using fmt=cert

---

README.md
auth_approle.go
config.go
tests/approle_auth_file.json
tests/approle_auth_file.yml

Allow setting a custom vault login path for approle backend 
Defaults to standard `/v1/auth/approle/login`
Add README section with described configuration / environment variables

Support custom login path for approle auth backend

---

vault.go

Currently, `time.Duration(secret.LeaseDuration)` is added to the current time to determine `leaseExpireTime`.  This is erroneous because `secret.LeaseDuration` is in seconds and `time.Duration` stores nanoseconds.  This causes `leaseExpireTime` to be effectively set to ~`time.Now()`.
Due to the above bug, `time.Now()` is always after `leaseExpireTime`, but the code also has a bug reversing the meaning of the lease expiration check so the lease-expired codepath is never taken.  This means that if a lease ever does expire (which we've seen when there are `vault` connectivity issues that last longer than the 5-20% cushion in the lease-renewal time) then `vault-sidekick` erroneously attempts to renew it forever even though it should really re-retrieve the resource.
Multiply the duration by …

Fix lease expiration checks to prevent permenently revoked resources after temporary `vault` issue

---

README.md
vault_resource.go
vault_resources.go

Allow ttl to be passed as a parameter for use with the Vault PKI backend.

Ttl config

---

vault.go

If a token (or its lease) is revoked its attempts to renew itself will fail with a `403: permission denied`.  Treat that case as a fatal errors since any credentials it's generated will have been revoked and it is unable to retrieve replacements.
If a resource (or its lease) is revoked its attempts to renew itself will fail with a `400: lease not found`.  Attempt to retrieve a new copy of the resource.
Also don't crash if secret can't be fetched:
If the secret wasn't found, `secret` and `err` would both be `nil` and `secret` would be dereferenced when checking to see if it was a v2 kv store causing a crash.

Don't (re)try to renew revoked tokens or resources (and fix crash)

---

Dockerfile
main.go

Alpine v3.5 ended support 2018-11-01 - this PR moves to Alpine v3.12 
Also bumped vault-sidekick version to v0.3.16

Move to latest alpine version 
