UKHomeOffice/vault-sidekick

- CONDUCT_CODE.md
- CONTRIBUTING.md
- README.md
- config.go
- main.go
- vault.go
- adding the ability to import a root CA rather bypassing the tls verfication
> CA root import

- config.go
- main.go
- utils.go
- vault.go
- vault_resource.go
> - adding the bundle format option

- config.go
- generate.go
- vault_resources.go
- vault_resources_test.go
- adding the ability to expansion environment variable in the resource path
> environment variable expansion

- .gitignore
- Dockerfile
- main.go
- utils.go
- changing the argument passed to the exec default filename i.e. either file=<FILE> or path.type
- fixing up the docker build
> - shifting the docker image to alpine:3.3

- CHANGELOG.md
- formats.go
- main.go
- shifting the version to v0.1.0
- fixing up the format of the bundle
> bundle format

- .travis.yml
- Makefile
- adding the step to publish a image
> - adding a build step to publish the binary

- Dockerfile
- README.md
- main.go
- updating the release version to v0.2.1
- updating the docker image to alpine:3.4
> - updating the README with badges

- .travis.yml
- config.go
- vault.go
- fixing the loading of the ca certificate for verification
> CA Certificate

- auth_token.go
- config.go
- utils.go
- vault.go
Related to this issue:
https://github.com/UKHomeOffice/vault-sidekick/issues/36
Thanks!
> Adding kubernetes-vault support - slightly different file format.

- config.go
- main.go
> Add one-shot mode

- CHANGELOG.md
- kube/deployment.yaml
> Release v0.3.2

- main.go
- utils.go
"[error] unable to create the vault client: unsupported authentication plugin: "
This fixes the problem for me.  Not sure if previous code wasn't tested or if I'm doing something wrong?
> fix for kubernetes-vault method being unset

- CHANGELOG.md
- main.go
- updated the changelog and the version
> Release 0.3.4

- README.md
Hi there, 
This is a great project!  I just started using it in combination with kubernetes-vault, and had a bit of confusion because I started out using the outdated image that lives on dockerhub. This minor doc tweak might help other users with the same confusion.
> update documentation to v0.3.3 

- CHANGELOG.md
- main.go
@gambol99 what do you think about a v0.3.5 release with the changes that were just merged?
> setup for v0.3.5 release

- CHANGELOG.md
- main.go
- adding the vault token renewal feature
> Release v0.3.6

- CHANGELOG.md
- main.go
- Adding a release and updating the changelog and version for v0.3.7
> Release v0.3.7

- CHANGELOG.md
- main.go
- updating to v0.3.9 which includes a kubernetes auth provider
> Release v0.3.8

- auth_token.go
reads the token from a file. works really nicely with the new `vault agent` functionality, so the `vault agent` manages the token and sidekick manages the secrets.
> auth/token: add support for token file

- formats.go
Hi,
The documentation inside the repos mention the bundle format exports certs + private key, but I found only ca + cert were exported.
This PR adds also the private key to the bundle.
> make sure the bundle exports the private key too (as per docs)
